name: build_push_image
description: Build and push image to Amazon ECR

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials and Assume Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_IMAGE_MANAGER_ROLE }}
        role-session-name: PushImage

    - name: Login to Amazon ECR
      id: login_ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set IMAGE_URI
      id: set_image_uri
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build, tag, and push image to Amazon ECR
      id: build_push_image
      shell: bash
      run: |
        # Build a docker container and push it to ECR
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    