name: Prettier

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10.2.1

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: marker
      run: echo "*********************"
      shell: bash

    - name: list files
      run: ls -la
      shell: bash

    - name: Prettify code
      uses: creyD/prettier_action@v4.3
      with:
        prettier_options: "--check --ignore-path .prettierignore src/**/*.{ts,js,tsx}"
        dry: true
        working_directory: "."