name: Test

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.15.1

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Run tests
      run: pnpm test
      shell: bash
