name: Install
description: Install dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.15.1

    - name: Cache node modules
      id: cache-pnpm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.local/share/pnpm/store/v3
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: ${{ steps.cache-pnpm.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      shell: bash
      run: ls -la ~/.local/share/pnpm/store/v3

    - name: Install dependencies
      run: pnpm install
      shell: bash
