name: Manually deploy to tagged release

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: development

env:
  DEPLOYER: ${{ github.actor }}
  IMAGE_TAG: "${{ github.ref_name }}-${{ github.sha }}"

jobs:
  build_push_image:
    name: Build and push
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    env: 
      AWS_IMAGE_MANAGER_ROLE: ${{ secrets.AWS_IMAGE_MANAGER_ROLE }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: build and push image
        uses: ./.github/actions/build_push_image
        with:
          image_tag: ${{ env.IMAGE_TAG }}
  
  trigger_deploy:
    needs: build_push_image
    name: Trigger deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Trigger deploy
        uses: ./.github/actions/trigger_deploy
        with:
          image_tag: ${{ env.IMAGE_TAG }}
          access_token: ${{ secrets.INFRASTRUCTURE_ACCESS_TOKEN }}
          secrets: |
            [
              {
                "name": "WEB_SERVICE_SECRETS", 
                "valueFrom": "${{ vars.WEB_SERVICE_SECRETS }}"
              },
              {
                "name": "ORG_SECRETS", 
                "valueFrom": "${{ vars.ORG_SECRETS }}"
              }
            ] 