name: Manually deploy to tagged release

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: development

env:
  DEPLOYER: ${{ github.actor }}
  TAG: ${{ github.ref_name }}
  SHA: ${{ github.sha }}

jobs:
  build-and-push-image:
    name: Build and push
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    env: 
      AWS_IMAGE_MANAGER_ROLE: ${{ secrets.AWS_IMAGE_MANAGER_ROLE }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$TAG-$SHA" >> $GITHUB_ENV

      - uses: ./.github/actions/build_push_image

      - uses: ./.github/actions/trigger_deploy
        with:
          image_tag: $IMAGE_TAG