name: Build Image and Push to ECR

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'development'

jobs:
  build-and-push-image:
    name: Build and push
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env: 
      AWS_IMAGE_MANAGER_ROLE: ${{ secrets.AWS_IMAGE_MANAGER_ROLE }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_push_image