name: Manually deploy to tagged release

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: development
      image_tag:
        required: false

env:
  DEPLOYER: ${{ github.actor }}
  INPUT_TAG: ${{ github.event.inputs.image_tag }}
  INPUT_IMAGE_TAG: "${{ github.event.inputs.image_tag }}-${{ github.sha }}"
  DEFAULT_IMAGE_TAG: "${{ github.ref_name }}-${{ github.sha }}"

jobs:
  build-and-push-image:
    name: Build and push
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    env: 
      AWS_IMAGE_MANAGER_ROLE: ${{ secrets.AWS_IMAGE_MANAGER_ROLE }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=($INPUT_TAG && $INPUT_IMAGE_TAG || DEFAULT_IMAGE_TAG)" >> $GITHUB_ENV

      - uses: ./.github/actions/build_push_image

      - uses: ./.github/actions/trigger_deploy
        with:
          image_tag: $IMAGE_TAG