name: Pre merge checks

on:
  pull_request:
    branches:
      - main

jobs:
  # install:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install
  #       uses: ./.github/actions/install

  lint:
    runs-on: ubuntu-latest
    # needs: install
    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: ./.github/actions/install

      - name: Lint
        run: pnpm -r lint

  prettier:
    runs-on: ubuntu-latest
    # needs: install
    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: ./.github/actions/install

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check **/src/**/*.{ts,js,tsx}

  build:
    runs-on: ubuntu-latest
    # needs: install
    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm -r build

  test:
    runs-on: ubuntu-latest
    # needs: install
    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: ./.github/actions/install

      - name: Run tests
        run: pnpm -r test
