name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.1
        name: Install pnpm

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check **/src/**/*.{ts,js,tsx}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.1'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm -r lint

      - name: Build
        run: pnpm -r build

      - name: Run tests
        run: pnpm -r test
