name: Pre merge checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Lint
        run: pnpm -r lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check **/src/**/*.{ts,js,tsx}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm -r build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Run tests
        run: pnpm -r test
