# Disabling this for now, images should be tagged before release
name: Automatic deploy to development

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    if: false
    name: Build and push
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: read
      id-token: write

    env: 
      AWS_IMAGE_MANAGER_ROLE: ${{ secrets.AWS_IMAGE_MANAGER_ROLE }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_push_image